"""
Pydantic schema for site inventory.

This module defines the data models used to validate and type-check
the site inventory generated by Agent 02 (CrawlAgent).

Classes:
    ImageInfo: Image metadata including optimization status
    OpenGraphTags: Open Graph meta tag values
    PageRecord: SEO data for a single crawled page
    CrawlError: Error information for failed crawls
    SitemapInfo: Sitemap.xml metadata
    RobotsTxtInfo: robots.txt metadata
    SiteInventorySchema: Complete site inventory
"""

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class ImageInfo(BaseModel):
    """Information about images on a page."""
    src: str
    alt: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    is_optimized: bool = False


class OpenGraphTags(BaseModel):
    """Open Graph meta tags."""
    og_title: Optional[str] = None
    og_description: Optional[str] = None
    og_image: Optional[str] = None
    og_url: Optional[str] = None
    og_type: Optional[str] = None
    og_site_name: Optional[str] = None


class PageRecord(BaseModel):
    """Record for a single crawled page."""
    # Basic info
    url: str
    status_code: int
    title: Optional[str] = None
    meta_description: Optional[str] = None
    
    # Headings
    h1: Optional[str] = None
    h2_tags: List[str] = Field(default_factory=list)
    h3_tags: List[str] = Field(default_factory=list)
    
    # Technical SEO
    canonical_url: Optional[str] = None
    is_https: bool = True
    robots_directive: Optional[str] = None
    
    # Open Graph / Social
    og_tags: Optional[OpenGraphTags] = None
    
    # Schema markup
    schema_markup: Optional[str] = None
    schema_types: List[str] = Field(default_factory=list)
    
    # Content metrics
    word_count: int = 0
    response_time_ms: int = 0
    
    # Media
    images: List[ImageInfo] = Field(default_factory=list)
    has_unoptimized_images: bool = False
    
    # Links
    internal_links: List[str] = Field(default_factory=list)
    external_links: List[str] = Field(default_factory=list)


class CrawlError(BaseModel):
    """Error record for failed crawls."""
    url: str
    error: str
    status_code: Optional[int] = None


class SitemapInfo(BaseModel):
    """Sitemap information."""
    found: bool = False
    url: Optional[str] = None
    pages_count: int = 0


class RobotsTxtInfo(BaseModel):
    """Robots.txt information."""
    found: bool = False
    url: Optional[str] = None
    allows_crawl: bool = True
    sitemaps: List[str] = Field(default_factory=list)


class SiteInventorySchema(BaseModel):
    """Complete site inventory schema."""
    # Crawl results
    total_pages: int = 0
    crawl_depth_reached: int = 0
    pages: List[PageRecord] = Field(default_factory=list)
    crawl_errors: List[CrawlError] = Field(default_factory=list)
    
    # Technical files
    sitemap: Optional[SitemapInfo] = None
    robots_txt: Optional[RobotsTxtInfo] = None
    
    # Security
    is_https_only: bool = True
    has_ssl_issues: bool = False
    
    # Duplicate content analysis
    duplicate_titles: List[Dict[str, str]] = Field(default_factory=list)
    duplicate_meta_descriptions: List[Dict[str, str]] = Field(default_factory=list)
    
    # Thin content
    thin_content_pages: List[Dict[str, str]] = Field(default_factory=list)
    
    # Summary
    pages_with_h1: int = 0
    pages_with_meta_description: int = 0
    pages_with_schema: int = 0
    pages_with_og_tags: int = 0
    avg_response_time_ms: float = 0.0
